version: '3.9'

services:
  backend:
    build: ./backend
    image: waelgharsalli/backend:latest 
    command: npm run start
    ports:
      - "3001:3001"

    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:wael01234@mongo:27017/catch-db-prod?authSource=admin

  frontend:
    build: ./frontend
    image: waelgharsalli/frontend:latest
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_URL=http://catchapp.com

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wael01234
    volumes:
      - catch-db-data:/data/db
    container_name: mongodb
    ports:
      - "27017:27017"


volumes:
  catch-db-data: {}
